### ISSUE TITLE
Idée : changer un paramètres de simpleModManager de atmosphère/contents a atmosphere

### ISSUE THREAD

**Issue by mathias-tavernier-roux** [shadow2560/switch_AIO_LS_pack#2]
Certains mods comme Super Mario Odyssey Online et Super Mario Odyssey Shadow Clones par exemple nécessite l'installation d'un composant du mod nommé StarlightBase dans exefs_patchs ce qui cause des problèmes lors du chargement avec simpleModManager
Vu qu'il est configuré pour uniquement modifier le dossier contents d'atmosphere

C'est un changement mineur qui pourrait être mis en place en même temps qu'une mise a jour du pack ou avec une option dans l'updater a condition qu'il ne pose pas de problème de sécurité évidement

Merci d'avance

**Comment by shadow2560** [comment]
On peut peut-être rajouter un preset de ce genre:

```
########################################
# preset that can be changed in the app
preset = atmosphere_no_contents_base_folder

# base folder where mods are installed
install-mods-base-folder = /atmosphere/
########################################
```

Sinon je ne pense pas changer ce paramètre car la majorité des mods n'en on pas besoin et seraient donc affectés par cette modification. Pour être plus clair en fait il faudrait utiliser le homebrew différemment de se qui est communément expliqué pour celui-ci se que je souhaite éviter.

**Comment by shadow2560** [comment]
Comme ça fait un moment que j'ai implémenté le profile dont j'ai parlé dans mon commentaire précédant et vu que je n'ai eu aucun retour je ferme cette issue que je considère comme étant réglée.
